# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEntraracorreo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_entraracorreo(self):
    self.driver.get("https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1612545787&rver=7.0.6737.0&wp=MBI_SSL&wreply=https%3a%2f%2foutlook.live.com%2fowa%2f%3fnlp%3d1%26RpsCsrfState%3d863fa5b3-4823-671e-175a-8dc85afa6a44&id=292841&aadredir=1&CBCXT=out&lw=1&fl=dob%2cflname%2cwld&cobrandid=90015")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.ID, "i0116").send_keys("vichofernando_10@hotmail.es")
    self.driver.find_element(By.ID, "i0118").send_keys("david1996")
    self.driver.find_element(By.ID, "i0116").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "idSIButton9").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_33rLSYbzxvhXjgYTwfjWQI > .ms-Button-flexContainer")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_33rLSYbzxvhXjgYTwfjWQI > .ms-Button-flexContainer").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_33rLSYbzxvhXjgYTwfjWQI > .ms-Button-flexContainer")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_4utP_vaqQ3UQZH0GEBVQe").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_4utP_vaqQ3UQZH0GEBVQe")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<div style=\"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);\">hola</div>'}", element)
  
